# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "1sfgkjddhvpcqsaq59m3y070i9kgm4g36qimrqa09g3cdqhmvv7l";
    x86_64-linux = "0b16v20y049savmhnliqrmcxpa0h416w8d8m5nzaqqalw3q41k6x";
    aarch64-linux = "1whxsw9i665grmd8mqzawnqvh7yg5vjb0qkd8xm83g4lr6shl4kg";
    x86_64-darwin = "08svv3aa5dcc5cplnlfkmb617d8z4mrdwcilx9s5k8r3by6aq36r";
    aarch64-darwin = "01l4ps74i3j7zkbfklgvqfyq4g05am0j3gj7vh688m3fsxscb1kh";
  };

  urlMap = {
    i686-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rift";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./rift $out/bin/rift
  '';

  system = system;

  meta = {
    description = "LoL Esports in your terminal";
    homepage = "https://github.com/matthieugusmini/rift";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
