# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "02a5mhpah8ycwglzp71pidyk8qcx05d3sridi2xfrcxg56biv9rm";
    x86_64-linux = "1rd1i1s758sb409p307rd0vr3gqqaqbg95fg370crm9gb2pivyjp";
    aarch64-linux = "05aglz26lcap3rkx8hv6ns1i6r1f54mn2m3lppjbxcvadlxjzgr0";
    x86_64-darwin = "0r6nr8swkan2fgxk5jnpr24g9qs5haffhx9m2swqik9nckbg5s23";
    aarch64-darwin = "0fmbqwqscrh1mrijd8jbnynrmlr753xfmqblbxxr9mb6hkb4w25x";
  };

  urlMap = {
    i686-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/matthieugusmini/rift/releases/download/v0.1.0/rift_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rift";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./rift $out/bin/rift
  '';

  system = system;

  meta = {
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
