# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "1dl11c4b0vjl0dzwqpcfq5lj11a6s571s5ybi1jgk74xihxq1ipj";
    x86_64-linux = "0aqwxbb5g32hc2v3xrn917bvxng4s3fd75g5l44h34q0p0skxl64";
    aarch64-linux = "014q3ywdf024wlakkg5l0j8xjsna7rdjkkwxspy330qk472w3ri3";
    x86_64-darwin = "1j7pkr56ypsbag0h1n1wxwa320h7d5cszydwnar75ch60fmpf0jv";
    aarch64-darwin = "01s4siwp9j9d5zfzclpw2qv46a77z94fi2y7w87kzg2hy96sw1p4";
  };

  urlMap = {
    i686-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/matthieugusmini/rift/releases/download/v0.1.1/rift_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "rift";
  version = "0.1.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./rift $out/bin/rift
  '';

  system = system;

  meta = {
    description = "LoL Esports in your terminal";
    homepage = "https://github.com/matthieugusmini/rift";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
